### ISSUE TITLE
[Feature Request] Support for BE468GBAK Schlage zigbee version

### ISSUE THREAD

**Issue by arsenicks** [FutureTense/lock-manager#84] opened 2021-05-25 22:52 UTC
**Is your feature request related to a problem? Please describe.**
The support for the Zigbee version of the schlage lock is really minimal(Lokc, unlock, set code, enable slot , disable slot, clear code), it would be awesome to extend the support of lock-manager to the zigbee version!

I know the manager in it's current form is probably built only with zwave in mind, do you think it could be extended to cover the zigbee version ?

**Comment by firstof9** [comment] 2021-05-25 23:20
Dupe of https://github.com/FutureTense/keymaster/issues/163

**Closed as completed by firstof9** 2021-05-25 23:20 UTC
Labels: duplicate

**Comment by arsenicks** [comment] 2021-05-25 23:54
Sorry, I searched for zigbee but didn't found any. Will subscribe. thanks!
