### ISSUE TITLE
ISSUE: I don't see the "Using OZW?" checkbox shown in install guide

### ISSUE THREAD

**Issue by sphanley** [FutureTense/lock-manager#77] opened 2020-12-31 16:41 UTC
When setting up a newly installed instance of Lock Manager 0.0.45, I do not see the "Using OZW?" checkbox which is mentioned in the wiki and shown in the screenshot. Has this been removed from current versions, or does this mean there's something wrong with my setup? I installed using HACS installed on a current release of Home Assistant Core. 

If this is in fact simply a case of outdated documentation, I'm happy to send a PR to update it - I'd also recommend adding a recommendation to reboot the server after installing the integration but before trying to add the Lovelace view, as it is not currently mentioned, and failing to do so will cause missing entities in the Lovelace.

**Comment by firstof9** [comment] 2020-12-31 16:55
Duplicate of #75

**Comment by firstof9** [comment] 2020-12-31 16:57
Docs will be updated on the next release.
There's a lot of changes coming.

**Comment by sphanley** [comment] 2020-12-31 16:59
Right on - looking forward to seeing what's coming. Thanks!

**Closed as completed** 2021-05-25 23:21 UTC
Labels: duplicate
